### ISSUE TITLE
Event Loops in the Wild

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#1]
[Icicle](https://github.com/icicleio/icicle/blob/master/src/Loop/Loop.php)

``` php
interface Loop
{
    public function tick(bool $blocking = true);
    public function run(callable $initialize = null): bool;
    public function stop();
    public function isRunning(): bool;
    public function clear();
    public function reInit();
    public function maxQueueDepth(int $depth = null): int;
    public function queue(callable $callback, array $args = []);
    public function poll($resource, callable $callback, $persistent = false, $data = null): Io;
    public function await($resource, callable $callback, $persistent = false, $data = null): Io;
    public function timer($interval, $periodic, callable $callback, $data = null): Timer;
    public function immediate(callable $callback, $data = null): Immediate;
    public function signal($signo, callable $callback, $data = null): Signal;
    public function signalHandlingEnabled(): bool;
}
```

[React](https://github.com/reactphp/event-loop/blob/master/src/LoopInterface.php)

``` php
interface LoopInterface
{
    public function addReadStream($stream, callable $listener);
    public function addWriteStream($stream, callable $listener);
    public function removeReadStream($stream);
    public function removeWriteStream($stream);
    public function removeStream($stream);
    public function addTimer($interval, callable $callback);
    public function addPeriodicTimer($interval, callable $callback);
    public function cancelTimer(TimerInterface $timer);
    public function isTimerActive(TimerInterface $timer);
    public function nextTick(callable $listener);
    public function futureTick(callable $listener);
    public function tick();
    public function run();
    public function stop();
}
```

[AMP](https://github.com/amphp/amp/blob/master/lib/Reactor.php)

``` php
interface Reactor
{
    const STOPPING = -1;
    const STOPPED  = 0;
    const STARTING = 1;
    const TICKING  = 2;
    const RUNNING  = 3;

    public function run(callable $onStart = null);
    public function tick($noWait = false);
    public function stop();
    public function immediately(callable $callback, array $options = []);
    public function once(callable $callback, $msDelay, array $options = []);
    public function repeat(callable $callback, $msInterval, array $options = []);
    public function onReadable($stream, callable $callback, array $options = []);
    public function onWritable($stream, callable $callback, array $options = []);
    public function onSignal($signo, callable $func, array $options = []);
    public function onError(callable $callback);
    public function cancel($watcherId);
    public function disable($watcherId);
    public function enable($watcherId);
    public function info();
}
```

**Comment by AndrewCarterUK** [comment]
This weekend I'll look at these interfaces and draw up the similarities and differences. From there we'll be able to look at the pros/cons of the different approaches and hopefully gain some insight as to why different design choices were made (and which choices we should make).

@WyriHaximus / @trowski - Any light you could shed on the reasoning behind design decisions within your respective projects would be helpful. Particularly in the areas where the approach taken differs from the others :)

**Comment by AndrewCarterUK** [comment]
My first thoughts are:
- I like to callable for 'onStart' offered by AMP and Icicle
- I think I prefer 'onReadable', 'onWritable' and 'on*' in general

**Comment by cboden** [comment]
While it hasn't seen any action in a while this has been discussed internally off and on in React; we were looking at [this PR](https://github.com/reactphp/event-loop/pull/16) for v2 of our event loop:

``` php
interface LoopInterface {
    public function onReadable($stream, callable $listener);
    public function enableRead($stream);
    public function disableRead($stream);
    public function onWritable($stream, callable $listener);
    public function enableWrite($stream);
    public function disableWrite($stream);
    public function remove($stream);
    public function addTimer($interval, callable $callback);
    public function addPeriodicTimer($interval, callable $callback);
    public function cancelTimer(TimerInterface $timer);
    public function isTimerActive(TimerInterface $timer);
    public function onNextTick(callable $listener);
    public function onFutureTick(callable $listener);
    public function tick();
    public function run();
    public function stop();
}
```

**Comment by WyriHaximus** [comment]
- As @AndrewCarterUK already points out the `on*` looks really nice and simple
- Not sure yes about the enable_/disable_ vs. cancel/enable/disable
- One thing I'm really interested in personally is AMP's `info` method to get a glimps into the state of the event loop, useful for debugging and monitoring.
- As with icicle and AMP only one tick/immediately method, react's future/next tick caused confusion. Where I would like to add that that a tick/immediately added from a tick/immediately should be executed in the next loop's iteration
- For timers I really like AMP's once/repeat, it's a bit less verbose then react's addTimer/addPeriodicTimer. But maybe timer/periodicTimer is an idea

**Comment by AndrewCarterUK** [comment]
@trowski / @assertchris - Do either of you have anything to add to this before I/we get cracking?

**Comment by trowski** [comment]
If we are going with a model that returns watcher IDs from event schedulers (and I think for simplicities sake we should), then I also like the `on*()` method names. With this model, I like Amp's style of a single `cancel()`, `disable()` and `enable()` methods that take watcher IDs and act accordingly. It keeps the interface clean, uncluttered with similar methods such as `cancelRead()` or `cancelTimer()`.

I also agree with @WyriHaximus that a single method for scheduling a function for execution in a future turn of the event loop makes sense. Personally I like the name I chose for Icicle: `queue()`.

I like Amp's `info()` method as well, but does it have to be part of the general interface? A debugging method doesn't seem like something that would be needed for interoperability.

For timers I also like the shorter method names. I of course prefer Icicle's `timer()`/`periodic()`, but `once()`/`repeat()` would also be acceptable.

Putting this all together, I suggest something like this for an interface:

``` php
interface EventLoop
{
    public function run(callable() $onStart = null): void;
    public function tick(bool $block = true): void;
    public function stop(): void;
    public function queue(callable(...$args) $callback, ...$args): void;
    public function timer(callable(int $watcherId, $data) $callback, float $time, $data = null): int;
    public function periodic(callable(int $watcherId, $data) $callback, float $interval, $data = null): int;
    public function onReadable($stream, callable($stream, int $watcherId, $data) $callback, $data = null): int;
    public function onWritable($stream, callable($stream, int $watcherId, $data) $callback, $data = null): int;
    public function onSignal(int $signo, callable(int $signal, int $watcherId, $data) $callback, $data = null): int;
    public function onError(callable(Throwable $exception) $callback): void;
    public function cancel(int $watcherId): void;
    public function disable(int $watcherId): void;
    public function enable(int $watcherId): void;
}
```

**Comment by AndrewCarterUK** [comment]
@trowski - would you gave any objections to replacing the watcher id with a 'Watcher' object/interface.

Separation of concerns would move the enable/disable/cancel methods onto that?

**Comment by AndrewCarterUK** [comment]
That would give:

``` php
interface EventLoop
{
    public function run(callable $onStart = null): void;
    public function tick(bool $block = true): void;
    public function stop(): void;
    public function queue(callable $callback, ...$args): void;
    public function timer(callable $callback, float $time, $data = null): Watcher;
    public function periodic(callable $callback, float $interval, $data = null): Watcher;
    public function onReadable($stream, callable $callback, $data = null): Watcher;
    public function onWritable($stream, callable $callback, $data = null): Watcher;
    public function onSignal(int $signo, callable $callback, $data = null): Watcher;
    public function onError(callable $callback): void;
}

interface Watcher
{
    public function cancel(): void;
    public function disable(): void;
    public function enable(): void;
    // Maybe
    public function getData(): mixed|null;
}
```

Edit: Just noticed that this approach would also allow us to remove the `$data`  parameter from the callback and add it to the `Watcher` with `Watcher::getData()`.

**Comment by AndrewCarterUK** [comment]
I think this thread has now moved past it's purpose of analysing the existing implementations.

As such, I recommend moving discussion on watcher identifiers or objects to #4.

I've also set up a working PR (#3) for more general discussion that should provide a better forum for working developments and discussion.
