### ISSUE TITLE
Loop::info

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#102]
This method currently doesn't match the other naming schemes. Should we rename it to `getInfo`? Any other name suggestions?

**Comment by bwoebi** [comment]
I see info() as an abbreviation of inform() … I do not see how getInfo() is more expressive/better conveying intent here.

**Comment by kelunik** [comment]
Maybe we should find a entirely new name like `getWatcherInfo` or `getWatcherStats`, because that's what it actually returns.

**Comment by bwoebi** [comment]
The _minimum_ info is only about watchers, yes. But implementations may want to add more loop specific info.

Apart from that `getWatcher*()` makes me expect the first parameter to be a watcher Id and get stats/info on that specific watcher.

**Comment by kelunik** [comment]
Maybe we should drop that minimum, as anything other isn't guaranteed to be there anyway. If you have to check for a specific implementation anyway if you want to use that data, you can call another specific method, too.

**Comment by bwoebi** [comment]
I see no explicit advantage of dropping that minimum.

**Comment by kelunik** [comment]
It doesn't encourage adding "unrelated" entries.

**Comment by bwoebi** [comment]
And that's an issue because…?

**Comment by kelunik** [comment]
Depends what you do with the data. If you use code like the following for submitting metrics, the code might break if other values are provided with a different structure.

``` php
foreach (Loop::info() as $type => $values) {
    foreach ($values as $prop => $count) {
        $metrics->count("{$type}.{$prop}", $count);
    }
}
```

**Comment by kelunik** [comment]
@trowski @joelwurtz What are your opinions on that? You put a reaction on the OP, but didn't comment here.

**Comment by trowski** [comment]
@kelunik I'd rather see the name be `getInfo()` purely for consistency. It might be nice to add `__debugInfo()` to the interface as an alias to this method.

**Comment by bwoebi** [comment]
@trowski I wouldn't recommend adding __debugInfo() to the interface (as in you shouldn't make magic funcs part of the interface). We may _recommend_ it, but I wouldn't force it.

**Comment by trowski** [comment]
Ok, that's reasonable, was just a random thought. :smile:

**Comment by kelunik** [comment]
@bwoebi You're the only one against, still have strong feelings against  `getInfo`?

@trowski @WyriHaximus What do you think about removing the _minimum_ and requiring those exact values?

**Comment by bwoebi** [comment]
Well, what shall I say… it's just a name. Names are subjective by definition. If I'm outnumbered here, then go with it.

I have stronger feelings about the _minimum_. I still see no issue with having it. It just is an artificial unnecessary limit.

**Comment by kelunik** [comment]
@bwoebi As I said in https://github.com/async-interop/event-loop/issues/102#issuecomment-258705894, it depends on how you consume those values.

**Comment by bwoebi** [comment]
That's why you should be aware of that and code appropriately.

**Comment by WyriHaximus** [comment]
@kelunik honestly I like the minimum as it gives flexibility for drivers to expose more values, and feel rather strongly about it. What we could do is require any additional values to be structured the same way as the minimum, for example:

```php
'foo' => [
    'bar' => 'bier',
],
```
