### ISSUE TITLE
Roadmap for projects implementing the interop project

### ISSUE THREAD

**Issue by PeeHaa** [async-interop/event-loop#105]
It would be nice to have a roadmap for the different projects to implement the interop standard. So we have some idea when and what projects will be compliant.

**Comment by kelunik** [comment]
We can't know which projects will implement this specification.

**Comment by assertchris** [comment]
This is the sort of thing that may be easier if we had a mini-site for the interop group.

We've not really been treating it as an individual body though, having started based on recommendations in FIG. Perhaps, when this and other specs are more stable, it wouldn't be such a bad idea to create that kind of mini-site. 

At that point, having a "enter your website address if you follow this spec" isn't onerous to make/maintain.

**Comment by kelunik** [comment]
I think this one is solved by the virtual package, no? https://packagist.org/providers/async-interop/event-loop-implementation
