### ISSUE TITLE
Detect active Loop

### ISSUE THREAD

**Issue by joelwurtz** [async-interop/event-loop#113]
See https://github.com/async-interop/promise/pull/17 which introduces the notion of active loop : 

> If there is no active loop, and one of the callbacks....

How do we check if there is or isn't an active loop ? I'm wondering if this should be specificied in this standard or we should do the following: 

```php
    function hasLoop()
    {
        try {
            Loop::get();

            return true;
        } catch (\LogicException $exception) {
            return false;
        }
    }
```

**Comment by kelunik** [comment]
We don't. This will be removed soon.

**Comment by bwoebi** [comment]
Depending on knowledge whether the loop is active is a bad idea, this was a bad decision in my PR and it rightfully got not merged in the promise repo.

**Comment by kelunik** [comment]
@joelwurtz Can I close this issue? You won't have to know whether a loop is active.

**Comment by joelwurtz** [comment]
Fine for me yes, thanks !
