### ISSUE TITLE
Root Namespace

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#128]
http://www.php-fig.org/psr/psr-4/ says the root namespace is the "vendor namespace", we aren't the "interop" vendor, we're the "async" vendor I'd say, but I don't feel strongly about it.

**Comment by bwoebi** [comment]
I don't care, that's just deciding on whether the paint of the shed needs to be a bit lighter or not...

**Comment by joshdifabio** [comment]
I really don't think the current two-level namespace makes a lot of sense. I think async-interop should use a single-level namespace to group its standards, and I think it'd be fine if that was _Async_ or _AsyncInterop_, although the latter would better reflect the name of the organisation.

**Comment by kelunik** [comment]
At least https://github.com/jderusse/async uses `Async` currently.

**Comment by kelunik** [comment]
https://bitbucket.org/mkjpryor/async/wiki/Home is another package using `Async`, found via http://packanalyst.com/.

**Comment by joshdifabio** [comment]
If we plan to use _async-interop_ as the Composer vendor name then I think it's least surprising to use _AsyncInterop_ as the namespace root.

**Comment by WyriHaximus** [comment]
> If we plan to use async-interop as the Composer vendor name then I think it's least surprising to use AsyncInterop as the namespace root.

I feel strongly about this strategy, this is the least confusing for users and both vendor namespace, composer namespace, and the Github vendor/org match :+1: .

**Comment by trowski** [comment]
The only reason I can see to continue with `Interop\Async` is that `container-interop` uses `Interop\Container`. Aside from that, `AsyncInterop` would be the obvious choice.
