### ISSUE TITLE
How to count in getInfo

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#131]
Reading https://github.com/WyriHaximus/reactphp-async-interop-loop/blob/33a8bfa/src/ReactEventLoop.php#L491-L499, should `referenced` / `unreferenced` include all watchers or only enabled ones?

**Comment by bwoebi** [comment]
Without checking what we do or what they do, I'd intuitively only consider enabled ones.
It doesn't provide much information to have disabled refd/unrefd info.

**Comment by WyriHaximus** [comment]
FYI IIRC I pretty much copied that over from AMP when writing that at the time, highly likely with some changes though :blush:

**Comment by bwoebi** [comment]
Closing as #135 has been merged.
