### ISSUE TITLE
Most methods in Loop checks for self::$driver else checks inside self::get()

### ISSUE THREAD

**Issue by brzuchal** [async-interop/event-loop#143]
Most of `Loop` mehtods have the same expression `$driver = self::$driver ?: self::get();` according to `self::get()` declaration there another check inside method `if (self::$driver)` whats the purpose of double check for driver already been set?

**Comment by kelunik** [comment]
The purpose here is saving a method call for maximum performance.

**Comment by brzuchal** [comment]
Nice, I didn't know that hack.I'm closing due to fact that it actually is not an issue if so.
