### ISSUE TITLE
Let's be mindful of the possibility of wanting things executed synchronously

### ISSUE THREAD

**Issue by assertchris** [async-interop/event-loop#15]
Following the Hangout of Async Interop vs. Fig inclusion: is it possible to force synchronous execution through these interfaces. I'm not asking this well, I think, but would it be possible to enter some always execute immediately mode of event loops? I'm going to ask the same question when we get to promises, but it probably needs to be asked here first.

**Comment by cboden** [comment]
Given this is an asynchronous body I would advise against any ability to have blocking I/O. If there is an execution order requirement I would suggest handling it via scheduling

**Comment by bwoebi** [comment]
I'm not sure if I understood the question correctly ...

There's only blocking execution by running a separate event loop and stopping it after some event (e.g. Promise resolved).

**Comment by kelunik** [comment]
@assertchris Could you clarify your question?

**Comment by assertchris** [comment]
Never mind, I've forgotten the original context of the question.
