### ISSUE TITLE
Timeouts on onReadable and onWritable

### ISSUE THREAD

**Issue by trowski** [async-interop/event-loop#23]
Many of the underlying event loop libraries support a timeout when polling a socket. Do we want to expose this capability in read/write watchers to avoid having to create a separate timer?

**Comment by bwoebi** [comment]
I don't really see how this doesn't violate SRP and is actually superior?
It creates more complexity and less obvious code `EventLoop::onReadable($stream, $cb, 1000);` ... wtf is that 1000?

``` php
$handle = EventLoop::onReadable($stream, $cb, 1000);
EventLoop::once(function() use ($handle) { EventLoop::cancel($handle); }, 1000);
```

Is much more obvious.

Additionally, you rarely have a pure timeout, but also want to fail a Promisor in these cases etc.

**Comment by kelunik** [comment]
I don't see the direct use case here, could you provide one, @trowski? Like @bwoebi said, I think you (almost) always have to fail a promisor or something like that.

**Comment by trowski** [comment]
With a single callback you can fulfill or reject the promisor in a single place. However then you need to have a parameter indicating if the watcher was invoked due to data or a timeout... which is what libev does and it's messy. I notice libuv doesn't support timeouts on polls for probably just this reason. Just thought I'd bring it up, I think the separation is better and agree with @bwoebi.

**Comment by assertchris** [comment]
Please leave these open for longer than a day.

**Comment by kelunik** [comment]
@assertchris Notifications should still arrive for everyone, even if it's closed. Or do you only have a look at the front page of issues? Then it might matter.

It was just an idea we quickly noticed isn't really practical.

**Comment by assertchris** [comment]
It's not a matter of notifications, but of involvement. If you start a conversation, and then close it before others have had a chance to participate, it encourages others not to participate as the topic can be perceived as closed.

Not the end of the world, but leaving it open for a little longer isn't troublesome either. We should be mindful of different timezones and availability.

**Comment by kelunik** [comment]
@trowski opened and closed it, if someone else had closed it, I'd fully agree. We can always reopen, as we already did with other topics in here. But fine, we can probably let the next one open for a longer time.

**Comment by assertchris** [comment]
@kelunik sure, that's fine.

**Comment by WyriHaximus** [comment]
For example, you filled up my github mail folder overnight, while I was sleeping, catching up takes a bit. It won't take two days during the weekend. But, some week days could be completely different.

I have no problem commenting and reopening issues but it can make feel left out.

@kelunik cheers :+1:

**Comment by kelunik** [comment]
I already said we can change that next time.

@WyriHaximus Just disable notifications and use web notifications on GitHub only. :stuck_out_tongue_winking_eye:

**Comment by WyriHaximus** [comment]
@kelunik it works for me, using email to keep track of notifications. Also my github feed can get hectic, with other OSS projects and work :wink:

**Comment by sagebind** [comment]
Yep, I have the same problem. :grinning: I'm either sleeping or busy when things happen.
