### ISSUE TITLE
The hardest problem: naming the Loop

### ISSUE THREAD

**Issue by bwoebi** [async-interop/event-loop#24]
Shall we really go by `EventLoop` or can we shorten the classnames to just `Loop`?

I've found it's not less meaningful, is more concise/easier to type and read.

This is obviously mainly a subjective thing... Feel free to disagree, just my personal opinion while looking at https://github.com/async-interop/event-loop-playground/blob/11b3492f5a78f53167cd4ebb54d9566c1fcb7263/run.php ... feels cleaner to me to have it called just `Loop`.

**Comment by AndrewCarterUK** [comment]
My thoughts:

## For
- Much easier to type, needs to be typed a lot

## Against
- Much less explicit (loop means lots of things in programming)
- Can be easily aliased

**Comment by bwoebi** [comment]
@AndrewCarterUK You typically have two types of loops: event loops and the language constructs. There are not many other Loops to my knowledge in (PHP) programming?

While it can be easily aliased, it may improve consistency throughout the sources. I can imagine EventLoop to be often aliased to Loop (but obviously not everyone will do that). But I can barely imagine Loop being aliased to EventLoop.
Thus I consider that actually an advantage, not a disadvantage.

**Comment by trowski** [comment]
+1 for `Loop`

**Comment by sagebind** [comment]
I'd vote for `Loop` as well. It's simpler, and I don't expect anyone to confuse it with anything else.

**Comment by kelunik** [comment]
+1 for `Loop`, even if `EventLoop` is anyway autocompleted. Also I think I'm for the static approach now instead of functions, it's nice to have all functions available as list when typing `EventLoop::`.

**Comment by AndrewCarterUK** [comment]
@kelunik - Interesting benefit nobody thought of!

Seems like people are in agreement here, PR anyone?

**Comment by kelunik** [comment]
Have a PR ready, could you give me push access? I don't want to synchronize all the time.

**Comment by AndrewCarterUK** [comment]
@kelunik - Happy to sort out push access, but one of the rules we agreed was that all repository changes come through pull requests that have been reviewed.

Know it seems pedantic, but it's the best time to set the standards we want to maintain is now :)

**Comment by kelunik** [comment]
I didn't want to push directly, just have one `origin`.

**Comment by bwoebi** [comment]
Was merged; closing.

**Comment by WyriHaximus** [comment]
+1 for `Loop`
