### ISSUE TITLE
Loop::execute and coroutines / testing

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#29]
We currently aren't coupled to any promise / coroutine / whatever API. This means that we can't use coroutines as an argument to `Loop::execute`. It might be possible to achieve it using something like `Amp\coroutine`.

My actual question is: How are we going to write tests? Using the an emulated `Loop::wait` / a decoupled `wait` function? The reason is that we need the thing that executes to throw exceptions thrown inside the callable to outside of the callable, so we can use things like PHPUnit's `@expectedException`.

**Comment by trowski** [comment]
If a callback throws an exception, implementations of `LoopDriver` should throw the exception from `run()`, so then it should be thrown from `Loop::execute()`.

**Comment by bwoebi** [comment]
I don't think this is the responsibility of the Loop class.

That's the responsibility of another library to bring promises and loop together.
Technically you have to write `Loop::execute(function() { resolve(function() { /* generator code */ })->when(function($e) { throw $e; }); })`
That other library may write a convenient wrapper for that.
