### ISSUE TITLE
Cluttering the `Interop\Async` namespace.

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#39]
Sorry, I should have noticed this when the original discussion came up to shorten the namespace.

Currently we have the `UnsupportedFeatureException` inside the `Interop\Async` namespace, which is obviously not ideal.

Should we wish to produce another standard that required a similar exception there would be a collision, or we would have to break consistency and things would be a mess.

I can see the following solutions:
- Change the namespace back to the longer form
- Create a `Loop` directory and move the driver and exception classes into there

I'm probably favouring the second option now, that would leave us with the following paths:

```
Interop\Async\Loop
Interop\Async\Loop\Driver (or LoopDriver)
Interop\Async\Loop\UnsupportedFeatureException
```

Interested to hear your thoughts.

**Comment by kelunik** [comment]
We could also rename `UnsupportedFeatureException` to `UnsupportedLoopFeatureException`.

**Comment by AndrewCarterUK** [comment]
It's an option, but I think ultimately namespaces exist to help collect/separate related/unreleated code.

I've no problem with us using the root namespace (`Interop\Async\Loop`) as a path, I don't think it's suitable to put code from unrelated standards into the same namespace.

**Comment by kelunik** [comment]
That said, I'm fine with the proposed solution.

Another thing to consider: How does the Composer autoloader work if there are two prefixes? Does it first take the longer prefix? Because otherwise, every class loaded in every standard will first try to load it from loop, then promise, then the real location.

If it takes the longer path first, we only have a double lookup for either `Loop` or `Promise`.

**Comment by joshdifabio** [comment]
> Another thing to consider: How does the Composer autoloader work if there are two prefixes? Does it first take the longer prefix? Because otherwise, every class loaded in every standard will first try to load it from loop, then promise, then the real location.

If people are concerned about autoload performance then I suppose they'll already be using Composer's optimized autoloader (`-o` option when running update/install), in which case it won't be an issue.

**Comment by bwoebi** [comment]
I prefer what @kelunik proposed: `UnsupportedLoopFeatureException`

At least if you import these classes, it somehow will be weird to read that in code `class UvDriver implements Driver` … what type of Driver? Sure the `use` tells you, but it reads a bit weird to me.
Same for UnsupportedFeatureException.

**Comment by kelunik** [comment]
> At least if you import these classes, it somehow will be weird to read that in code class UvDriver implements Driver … what type of Driver? Sure the use tells you, but it reads a bit weird to me.

But you still call it `UvDriver` instead of `UvLoopDriver`? I think it's pretty clear that you're in the event loop package.

**Comment by AndrewCarterUK** [comment]
I don't mind if people want to add the word loop back into the class names (I think it was `LoopDriver` originally anyway, `UnsupportedLoopFeatureException` might be a bit too verbose).

My main concern is having unrelated code in the same namespace. When I thought it was going to be just `Loop` and `LoopDriver`, that didn't ring alarm bells.

I still think the best solution is the second that I produced in the original post. As I said, namespaces were designed to separate unrelated code. It also helps IDE suggestions.

**Comment by kelunik** [comment]
Actually, `UnsupportedFeatureException` could be used by multiple proposals, not only the loop. There's no reason to have two, three or four `UnsupportedFeatureException`, just like everyone invents their own `InvalidArgumentException` currently.

**Comment by AndrewCarterUK** [comment]
@kelunik - We can't make those type of predictions about code we haven't written. How will we know that there wont be a new method that some proposals want on the unsupported feature exception for retrieving information about the feature?

It's a lot of guess work, and these standards should be decoupled.

**Comment by bwoebi** [comment]
@AndrewCarterUK then they shall create a specific one extending the current one.

**Comment by AndrewCarterUK** [comment]
@bwoebi - That would require it to include the event loop standard as a composer dependency. I think it's obvious that we should decouple all of the standards.

**Comment by bwoebi** [comment]
We may decouple the standards between each other, but have a common dependency between all async standards.

**Comment by kelunik** [comment]
@bwoebi We don't need that dependency, so let's not have it.

Let's go with the initially suggested change in the first post: `Async\Interop\Loop`, `Async\Interop\Loop\Driver` and `Async\Interop\Loop\UnsupportedFeatureException`.

**Comment by bwoebi** [comment]
Thinking about it, I'm not opposed to what @AndrewCarterUK proposed.
I think the current way is a bit better. But I don't strongly object against this proposal.

**Comment by bwoebi** [comment]
Done per PR #62.
