### ISSUE TITLE
Location of class constants

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#41]
Just noticed that the phpdoc says the feature class constants are on the static proxy (https://github.com/async-interop/event-loop/blob/master/src/Loop.php#L217) but they are actually defined on the loop driver.

I think the phpdoc is right here, but there is discussion to be had (it could even be on both or a separate interface).

**Comment by kelunik** [comment]
Both is a bad idea, we have to keep things in sync and it doesn't have any benefit. It will just confuse people, which one should I use now?

We could also move them to `LoopFeature::XY`.

**Comment by AndrewCarterUK** [comment]
I agree, as I said - I think we should go with putting them on the static proxy. For consumers, they'll already have this `use`'d in their classes.

**Comment by joshdifabio** [comment]
> We could also move them to `LoopFeature::XY`.

Personally, I like that approach best; it's more expressive and is the closest thing we have to enums in PHP.

**Comment by AndrewCarterUK** [comment]
I'm happy with either of those solutions.

**Comment by bwoebi** [comment]
I personally prefer having it all in one file/class. Should be easier for users too.

**Comment by bwoebi** [comment]
Let's defer this until #50 is resolved, as in this case this discussion is obsolete.
