### ISSUE TITLE
Loop::info

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#44]
Amp has `Amp\info` to inspect the loop. This can be useful for metrics or debugging.

https://github.com/amphp/amp/blob/master/lib/Reactor.php#L138-L160

**Comment by AndrewCarterUK** [comment]
I don't have any problem with this, I can see how it would be useful.

Wouldn't it make sense to return an array of ids:

```
     *  [
     *      "on_readable"   => ["enabled" => [id], "disabled" => [id]],
     *  ];
     *
```

Rather than a count:

```
     *  [
     *      "on_readable"   => ["enabled" => int, "disabled" => int],
     *  ];
     *
```

**Comment by sagebind** [comment]
I don't imagine any of the keys in the array to be part of the standard. Merely asking, "Hey loop, tell me everything you can about what's happening right now."

**Comment by kelunik** [comment]
AndrewCarterUK I don't think that's a good idea. Watchers should only ever be touched by the one that created them.

**Comment by WyriHaximus** [comment]
As coming up in #48, do we want to (partly) standardize the results coming from `info`?

**Comment by kelunik** [comment]
I propose to use the same keys as in Amp (of course change `immediately` to `defer` etc.), except for `state`.

**Comment by kelunik** [comment]
I added a PR, please share your opinion.
