### ISSUE TITLE
EventLoop or EventLoopInterface

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#5]
Should we add the word 'Interface' to the end of the interface class paths?

PSRs [3](http://www.php-fig.org/psr/psr-3/), [6](http://www.php-fig.org/psr/psr-6/) and [7](http://www.php-fig.org/psr/psr-7/) do (except in PSR-6 for the exception interfaces).

Created an issue for this as I know there are people who don't agree with doing this (indeed it isn't done in Icicle or AMP).

My personal vote is consistency with existing PSRs.

**Comment by assertchris** [comment]
Inclined towards consistency with other PSRs as well...

**Comment by oanhnn** [comment]
I am agree adding 'Interface'.
This like PSR 3, 6 and 7, [container-interop](https://github.com/container-interop/container-interop)

**Comment by WyriHaximus** [comment]
:+1: for consistency with other PSRs

**Comment by mnapoli** [comment]
Hi all! We had the same reasons for having the suffix in container-interop, and that's the only thing I regret ;) (the interface name is sooo long and unreadable compared to what it could be…). Maybe it's too late to change the FIG's internal conventions, but I wish it was possible. Right now new container's interop classes (still WIP, not stable) don't follow this convention, I don't know if it will stay like that until the stable version…

**Comment by kelunik** [comment]
Drop the interface! It's such a non-sense to write type declarations always with such a long name.

**Comment by bwoebi** [comment]
Yes, please drop the suffix. It's a general flaw of the PSRs.

**Comment by localheinz** [comment]
:+1: Consistency wins!

**Comment by AndrewCarterUK** [comment]
I asked FIG for opinions: https://groups.google.com/forum/#!topic/php-fig/Zgfd0gHUUoc

**Comment by kelunik** [comment]
@AndrewCarterUK It's clear what FIG says: It's a requirement.

**Comment by bwoebi** [comment]
@AndrewCarterUK not sure if that discussion is going to be very productive … you should rather ask what their rationale behind this is.

**Comment by assertchris** [comment]
Please consider, if we drop the suffix, it will be a valid reason for people to vote against the entrance of this PSR. We have to overturn the suffix precedent or accept that there will be people voting (justifiably) against the PSR on the basis of this inconsistency.

**Comment by kelunik** [comment]
@assertchris It's a bylaw, it won't be accepted as PSR without that suffix. We either have to change the bylaw or have async standards published by our own group separate from FIG. Since FIG is totally synchronous anyway, it could even make sense to separate all async things into a separate group.

**Comment by assertchris** [comment]
That's an interesting idea. Perhaps we should explore it further...

**Comment by WyriHaximus** [comment]
Interesting idea. AIG/Async Interop Group?

**Comment by assertchris** [comment]
Let's move that discussion here: https://github.com/async-interop/event-loop/issues/11

**Comment by assertchris** [comment]
Are we in agreement about dropping the Interface suffix? Could this issue be closed as resolved?

**Comment by sagebind** [comment]
I think in light of the previous discussion involving FIG, we are probably good to drop the suffix.

**Comment by AndrewCarterUK** [comment]
There's a second part to this question that complicates things slightly over here: https://github.com/async-interop/event-loop/issues/14

If we do go down the route of a static proxy class to an underlying event loop driver then the proxy class could be named `EventLoop` and the underlying driver could have to implement the `EventLoopInterface`:

``` php
class LibEvLoop implements EventLoopInterface { ... }

EventLoop::execute(function () {
    // ...

    EventLoop::onReadable($stream, function ($stream) {
        // do handling
    });

    // ...
}, new LibEvLoop());
```

What's being discussed really is quite a bold design move - so I'd appreciate some sceptical eyes on it before we travelled too far down that road - but it obviously would have implications for the question on naming conventions.

**Comment by kelunik** [comment]
If we use functions instead of static methods, we don't have that problem. We can easily call it `interface EventLoop`. :stuck_out_tongue_winking_eye:

**Comment by AndrewCarterUK** [comment]
If we use functions we lose encapsulation.

**Comment by kelunik** [comment]
Where do we loose encapsulation if we [do it like Amp does](https://github.com/amphp/amp/blob/master/lib/functions.php#L11-L20)? What exactly should be encapsulated?

**Comment by AndrewCarterUK** [comment]
The underlying event loop driver should be encapsulated. AMP uses the `reactor()` function to encapsulate the active reactor. I've got several problems with that design, all of these are solved by proper encapsulation using a class:
- `reactor()` is a function which actually has two functions - getting and setting the reactor.
- It doesn't make it possible (or at least clean) to stack multiple event loops (to run one inside another)
- There is no way to make the `reactor()` function drop its reference to the underlying event loop driver.

On the other hand, I can't see a single advantage that functions would have over a static class.

We have to find a middle ground between the boiler plate code of passing the event loop around and injecting it as a dependency everywhere and global objects that have no obvious end-of-life and leave hidden references. I believe we're getting very close to that in the other thread, with the concept of running a callable within the scope of an event loop and having that loop being detached once that scope has been left. It gives a very clear start and end point to the life of an event loop.

**Comment by bwoebi** [comment]
Is it that bad to have the reactor() function get and set? I see nothing wrong with that.

I don't see any implementation wise problems for stacking? Not sure what the problem would be.

Not sure what you mean with dropping the reference to the underlying driver? Just reset the value to null?

The advantage though would be that you can easily add functions when you have some reason to extend your concrete implementation by some function which isn't mandated by the interface.

So, I don't see any advantage of static classes, only a potential disadvantage.

Bob Weinand (iPhone)

**Comment by AndrewCarterUK** [comment]
@bwoebi - You can't reset the value to null, because that's the same as not passing a parameter, which is the same as asking it to 'get' rather than 'set'. It's a definite memory leak, you'd need to replace it with a null object to get it to drop the reference.

My opinion is that having a single function that performs two functions is bad design. In all my experience programming, I've found that simple functions with clear and obvious intentions are more maintainable, understandable and produce cleaner code that is easier to read. I don't think I'm alone in this, as I hear similar design practices at conferences and in programming material that I read online. The hidden reference in the `reactor()` function is a single example of the multitude of issues that can present themselves when functions aren't kept simple.

I'm not factoring extensibility into the design goals of the work we are doing here (allowing people to add functionality beyond what is provided by the standard). As soon as an implementation adds functionality beyond the specification - they aren't using the standard - because they can't guarantee that implementations of the standard will be interoperable with them. The obvious example with this is the Slim helper methods for PSR-7 - they are effectively useless for writing interoperable code - because people couple themselves to the Slim implementation of PSR-7 rather than PSR-7. These applications break if people try using Zend PSR-7 objects and they break in a very nasty way that isn't usually detected by unit tests (only smart functional tests that can foresee the problem).

With regards to stacking, the problem is that with a `reactor()` style function is that any code at any time can change the event loop for the whole application.

With a static class I can **guarantee** that (in the scenario below) I am using the event loop that I specified - and that some external library hasn't interfered with the driver that I am proxying to. With the AMP design, any library at any time could call the reactor function and my application simply can't assume that the event loop it originally specified was the one it is actually communicating with.

``` php
EventLoop::execute(function () {

   // call another library
   // do something else

   EventLoop::execute(function () {
     // this call is guaranteed to use OtherEventLoopDriver
     EventLoop::onReadable($stream, ...);
   }, new OtherEventLoopDriver());

   // this call is guaranteed to use EventLoopDriver
   EventLoop::onReadable($stream, ...);

}, new EventLoopDriver());
```

**Comment by sagebind** [comment]
> You can't reset the value to null, because that's the same as not passing a parameter, which is the same as asking it to 'get' rather than 'set'.

I think @AndrewCarterUK makes an interesting point here. It may certainly be useful to drop the event loop instance, especially when working with fickle things like threads or forked processes.

However, making it a static class isn't what offers you the guarantee of a particular event loop; its the use of closures. You _could_ write a static function that does the same thing as `EventLoop::execute`, but there would be no way for `onReadable` to access the current instance.

Either way, this kind of depends on #14, unless they have a different name. Like `interface Loop` and `class EventLoop`. No conflict that way, I suppose.

**Comment by AndrewCarterUK** [comment]
@coderstephen - What if my closure calls some third party library that has a call in it to the `reactor()` function?

It's impossible to guarantee without proper encapsulation.

**Comment by sagebind** [comment]
I was suggesting to not have a `reactor()` function, only an `execute()` function.

**Comment by AndrewCarterUK** [comment]
But then what would encapsulate the event loop? With functions there's no way of making something private - so you either need a function such as `reactor()` to encapsulate it or leave it as a global variable hanging around somewhere. Either way it's impossible to guarantee the scope of the event loop.

These are all solved problems!

**Comment by sagebind** [comment]
I don't believe it is technically possible using functions. I was just clarifying the reasons behind the stance, and then why the particular approach doesn't work with static functions.

**Comment by AndrewCarterUK** [comment]
@coderstephen Back to your earleir point, there is an option for going back to just different names.

I'm not a fan of 'EventLoop' and 'Loop'  - they're the same thing and it'd be easy to confuse them.

I'm thinking that leads us to `EventLoop` and `EventLoopDriver` - as that explains more clearly what they would do.

On that reasoning we can close this - as @assertchris said the discussion about the interface suffix has closed.

**Comment by sagebind** [comment]
> I'm thinking that leads us to `EventLoop` and `EventLoopDriver` - as that explains more clearly what they would do.

Ooh, I sort of like that.

But yes, the reasons for this issue have been resolved.
