### ISSUE TITLE
Parameter order for delay and repeat

### ISSUE THREAD

**Issue by joshdifabio** [async-interop/event-loop#54]
I noticed that for both `delay()` and `repeat()` the callback param comes before the time/interval param. This is the same as Amp's reactor interface but different to Icicle and React's event loop interfaces which both place the time/interval param first. The current approach results in code like the following:

``` php
$reactor->delay(function () {
    //lots
    //of
    //code
    //here
    //...
    //...
}, 1000);
```

versus the alternative

``` php
$reactor->delay(1000, function () {
    //lots
    //of
    //code
    //here
    //...
    //...
});
```

The latter seems much easier to grok, which I noticed when re-factoring some code from React\EventLoop today. Has this been discussed or are people pretty happy with the Amp ordering of params?

Note that `onReadable`, `onWritable` and `onSignal` all require the stream/signal nr. params before the callbacks in the current interface, so it's not like the callback is always placed first for consistency reasons.

**Comment by bwoebi** [comment]
There is the same problem with $cbData though. Which needs to be at the end being optional.
Though you may argue here that you typically don't use $cbData alongside with Closure, but rather use `use ()` construct with Closures.

I think I can get on board with this one.

**Comment by kelunik** [comment]
Yes, this has been discussed, at least somehow: https://github.com/async-interop/event-loop/issues/6

**Comment by bwoebi** [comment]
@kelunik not quite, the discussion was rather about putting $stream and $signal _after_ the callback too.

This is proposing the inverse and also brings in a good point.

**Comment by kelunik** [comment]
Yes, but we had that point back then, too.

**Comment by bwoebi** [comment]
@kelunik  don't find that particular point there.

We've mostly decided based on the _natural language interpretation_.

But you can write this as well as "Delay $x milliseconds, then do $y".

**Comment by joshdifabio** [comment]
Thanks for the link. I agree with @bwoebi that it doesn't look like it was discussed fully in #6, but I'll leave you guys who are stakeholders to discuss this. If you want to close the issue then I won't take offence.

**Comment by kelunik** [comment]
@joshdifabio See the last two comments there. I even said back then that we can only close it if we don't want to discuss parameter order there. ^^

**Comment by joshdifabio** [comment]
I saw that comment, but it was made after the issue was already closed, which is why I said I don't think it was discussed _fully_.

**Comment by kelunik** [comment]
Yes, and I agree.
