### ISSUE TITLE
Timer and Periodic Timer (And Queue)

### ISSUE THREAD

**Issue by AndrewCarterUK** [async-interop/event-loop#6]
Summary of discussion so far:

@assertchris prefers AMP's `once()` and `repeat()`
@trowski prefers Icicle's `timer()` and `periodic()` but says that `once()` and `repeat()` would also be acceptable.
@WyriHaximus really likes AMP's `once()` and `repeat()` but also suggests `timer()` and `periodicTimer()`

I'm going to make things difficult, as I think that `once()` could quite easily be confused with `queue()` - as this is also something that is run "once". 

Indeed, for AMPs interface they currently have:

``` php
public function immediately(callable $callback, array $options = []);
public function once(callable $callback, $msDelay, array $options = []);
```

I think what their interface would be clearer it used `delay`, as this is the difference between the two methods.

``` php
public function immediately(callable $callback, array $options = []);
public function delay(callable $callback, $msDelay, array $options = []);
```

I think this also raises a question about whether we use `queue()` or `immediately()`. For me these have different meanings, `queue` meaning we'll get around to it and `immediately` meaning the next thing that happens. Which here is more accurate?

My current vote would be for `delay()` and `repeat()` - interested to hear your thoughts!

**Comment by trowski** [comment]
I don't like the name `immediately()` because the function may not be executed immediately after leaving the current scope. It is usually not the next thing that gets executed. I think `queue()` is a more appropriate name for how the function behaves.

Let's look at event loops in some other languages/libraries and their equivalents for what I proposed to be named `timer()` and `periodic()`
- JavaScript: `setTimeout()` / `setInterval()`
- glib: None (make a repeating timer and cancel after first invocation) / `g_timeout_add()`
- libuv: `uv_timer_*()` (repeat param = 0) / `uv_timer_*()` (repeat param non-zero)
- libev: `ev_timer_*()` (repeat param = 0) / `ev_timer_*()` (repeat param non-zero) (libev also has `ev_periodic_*()` functions that create timers based on wall-clock time, something we aren't looking at supporting directly).

Honestly I was hoping that would be more informative when I started researching. If you can think of other examples feel free to mention them. The only conclusion I can really draw is that `timer` is a common label for executing a function after an interval of time passes.

Perhaps we could do a single `timer()` method with a repeat interval parameter as in libuv and libev?

My vote is still for `queue()`, `timer()`, and `periodic()` as I feel they are more immediately recognizable and self-explanatory, but an acceptable alternative would be `queue()`, `delay()`, `repeat()`.

Another idea would be to make all the watcher-returning methods be named as `on*()`, such as `onTimeout()` and `onInterval()`.

**Comment by AndrewCarterUK** [comment]
Let's stick with `queue()` then.

I like the consistency of all watcher-returnnig methods named as `on*()`.  Otherwise I'm impartial between `timer()`/`periodic()` and `delay()`/`repeat()`.

**Comment by WyriHaximus** [comment]
`queue()` sounds good.

I'm impartial whether we go for `timer()` / `periodic()` or `timer()` / `periodicTimer()`. The latter is more explicit but I prefer to keep it simple. And if the naming between two possible names for a method is nearly identical and unambiguous go for the shorter one word name.

Also `timer()` / `periodic()` is more explicit then `delay()` / `repeat()`.

**Comment by AndrewCarterUK** [comment]
I think if we went for the `onTimeout()` and `onInterval()` we would then have to rename `queue()` to be something like `onFutureTick()`.

That would give us an interface like this:

``` php
interface EventLoopInterface
{
    public function run(callable $onStart = null);
    public function tick(bool $block = true);
    public function stop();

    public function onReadable($stream, callable $callback, $data = null): WatcherInterface;
    public function onWritable($stream, callable $callback, $data = null): WatcherInterface;
    public function onSignal(int $signo, callable $callback, $data = null): WatcherInterface;
    public function onError(callable $callback, $data = null): WatcherInterface;
    public function onFutureTick(callable $callback, $data = null): WatcherInterface;
    public function onTimeout(float $time, callable $callback, $data = null): WatcherInterface;
    public function onInterval(float $interval, callable $callback, $data = null): WatcherInterface;
}
```

At the end of the day, any time you're adding a callback to the loop you are scheduling code to be run **on** an event. So consistency there makes sense. Sure we lose a short method name, but I think a function name that is explicit and obvious is probably more useful than one which is a few characters shorter.

**Comment by trowski** [comment]
`queue()` should not return a watcher. It should just execute the function next chance it gets with no going back. Essentially you should think of it as the same way as actually executing the function. No need for it to have an `on*()` name if we went that route.

**Comment by AndrewCarterUK** [comment]
Just a note to any readers to say this discussion is also happening in #7

**Comment by kelunik** [comment]
I'm clearly for `delay()` / `repeat()`. Function names should be verbs. I'm fine with both, `queue()` and `immediately()`. These functions schedule something, they're not really reactions to events like `onReadable` IMO.

**Comment by kelunik** [comment]
Actually, I'm for `queue()` since it's also a verb.

**Comment by bwoebi** [comment]
The issue with `queue()` is that it doesn't say to what queue.

`delay()` and `repeat()` are good choices. I like `immediately()` (bias by being used to it), but I'm open for alternatives … just not `queue()` please.

@AndrewCarterUK why are you proposing floats for times? The precision of the reactors/loops is one millisecond. (Some do allow for more, but e.g. for uv it's at most one millisecond. And we should be able to get same results for each backend.) At least that's the reason why Amp choose to use milliseconds as base unit and should be retained here.

**Comment by trowski** [comment]
@bwoebi Perhaps someday there can be greater precision than 1 ms. Using a float allows for that.

**Comment by kelunik** [comment]
Oh, I didn't get that `float` is proposed here. I'm really for `int` and milliseconds as unit of time.

@bwoebi `queue()` says as much about what to queue as `repeat()` or `delay()` say about what to repeat or delay.

@trowski Even if we could use greater precision than 1 ms, do you think there's a use case for such a thing in `repeat()` / `delay()`?

**Comment by bwoebi** [comment]
@kelunik Eih… I said _to what queue_, not _what to queue_. Is it a queue of callables to call as soon as possible? A queue of callables to call as soon as the reactor is ended…?

@trowski If there will ever be, it will be a BC break (significant enough for a major I mean) anyway as currently we should guarantee that all the backends use the same granularity for time management and that granularity would be changed too.

**Comment by kelunik** [comment]
Other possible names:
- `onNext()` ← Preferred.
- `onNextTick()` ← Preferred.
- `onTick()` ← Ambiguous, might be executed on every tick?

**Comment by bwoebi** [comment]
I don't see any advantage between `onNext()` and `next()` … so, `next()` would be fine to me :-) (also it's short, nice plus)

**Comment by kelunik** [comment]
It's not a verb like `delay` or `repeat`, but rather an event like `onReadable`, that's why I added the `on`.

**Comment by bwoebi** [comment]
`onNext` sounds weird to me though. (at least compared to `onNextTick` which is pretty long then... (and talks about ticks, which shouldn't be really exposed either.))

**Comment by kelunik** [comment]
`defer()` might be another choice, but it could be confused with `delay()`.

**Comment by bwoebi** [comment]
`defer()` without a $delay argument will be hardly confused I guess … I could live with it too :-)

**Comment by kelunik** [comment]
`delay()` with the delay set to `0` might be an option, too.

**Comment by bwoebi** [comment]
I was wondering the same, but we maybe still should have a direct method for such a common case?

**Comment by kelunik** [comment]
What about parameter order?

``` php
interface EventLoop {
    public function run(callable $onStart = null);
    public function stop();

    public function onReadable($stream, callable $callback, array $options = []): string;
    public function onWritable($stream, callable $callback, array $options = []): string;
    public function onSignal(int $signal, callable $callback, array $options = []): string;
    public function onError(callable $callback, array $options = []): string;

    public function defer(callable $callback, array $options = []): string;
    public function delay(callable $callback, float $msDelay, array $options = []): string;
    public function repeat(callable $callback, float $msInterval, array $options = []): string;

    public function enable(string $watcherId): void;
    public function disable(string $watcherId): void;
    public function cancel(string $watcherId): void;

    /* public function info(): array; */
}
```

**Comment by AndrewCarterUK** [comment]
@kelunik - If the callback is after the `$stream` and `$signal` parameters it should also be after the `$msDelay` and `$msInterval` IMO.

**Comment by bwoebi** [comment]
I agree, callback should be everywhere the first argument.
That makes it consistent and much more intuitive to remember what argument order is even without IDE autocompletion.

**Comment by kelunik** [comment]
I don't know, it fees strange for `onReadable` etc. to have the `$stream` after `callable`, because the `$stream` parameter feels more important there.

**Comment by bwoebi** [comment]
Well, you have a point here … if you read onReadable:
`on readability of $stream do $callback` … simple.
With repeat not so much:
`repeat every $msInterval milliseconds $callback` … or rather `repeat $callback every $msInterval milliseconds`.

So, I'm not sure.

**Comment by AndrewCarterUK** [comment]
Regarding names, I'm quite in favour of what @kelunik last posted.

`run()` and `stop()` control the loop.

`on*()` methods register a callback for an event that **might** happen. There is no guarantee that an error or a signal will occur, nor that a stream will ever be readable or writable.

`defer()`, `delay()` and `repeat()` are for events that are guaranteed (given enough time) to occur. In that sense, they are more predictable than the `on*()` methods which rely on external factors that are not necessarily within the control scope of the event loop - thus a different naming convention is appropriate. 

`enable()`, `cancel()` and `disable()` control the watchers.

**Comment by bwoebi** [comment]
Very nice summary … at least I can agree on that :-)

**Comment by sagebind** [comment]
Well said. I can't disagree with that logical reasoning.

**Comment by WyriHaximus** [comment]
Very well said, also in favor of that

**Comment by AndrewCarterUK** [comment]
Closing this now, if anyone has anything to add just comment and I will re-open.

**Comment by kelunik** [comment]
As long as we don't want to discuss parameter order here, that's fine.

**Comment by AndrewCarterUK** [comment]
I'm personally happy with what your natural language interpretation.

"on [something] becoming readable do [operation]"
"delay [operation] for this [time]"

If anyone else disagrees I'd suggest they create a new issue (as it is a separate topic)
