### ISSUE TITLE
Throw an exception on Driver::stop() without loop running

### ISSUE THREAD

**Issue by bwoebi** [async-interop/event-loop#66]
Shall we throw an exception here? Or rather not?

Having it unspecified is probably not the best idea.

I prefer throwing here.

**Comment by kelunik** [comment]
I prefer not. There may be multiple promises, each stopping the loop on resolution. They may succeed in the same tick.

**Comment by bwoebi** [comment]
Hmm, good point…

Did not think about the fact that stop() only takes effect on the end of a tick… Yeah … then it should be probably documented explicitly that it does _not_ throw (on the Driver).

**Comment by bwoebi** [comment]
Oh, why needs pull request … It's already mentioned… closing then…
