### ISSUE TITLE
Validity scope of defer() and once() watcher ids

### ISSUE THREAD

**Issue by bwoebi** [async-interop/event-loop#70]
When exactly becomes a defer()/once() watcher id invalid? _Before_ the callback call (as you anyway cannot do meaningful disable/enable on it inside the callback) or only _after_ it?

This needs to be specified in the Driver interface.

**Comment by kelunik** [comment]
I'd say before.

**Comment by WyriHaximus** [comment]
I'd also say before.

**Comment by joshdifabio** [comment]
I agree with _before_.

**Comment by bwoebi** [comment]
Good, that's fine. I'll do a simple PR documenting that soon.
