### ISSUE TITLE
Adding the others as maintainers on Packagist

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#82]
All major contributors should be maintainers IMO, see https://packagist.org/packages/async-interop/event-loop. @assertchris @WyriHaximus @trowski @AndrewCarterUK

**Comment by sagebind** [comment]
:+1:

**Comment by WyriHaximus** [comment]
👍

**Comment by kelunik** [comment]
@WyriHaximus You're in power. ;-)

**Comment by trowski** [comment]
Done. :santa:
