### ISSUE TITLE
List participating projects in README

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#83]
I guess it would be fine having them listed in the README. Suggestion comes from https://www.reddit.com/r/PHP/comments/4t6ggs/first_draft_version_of_the_eventloop/d5ezhqg

**Comment by bwoebi** [comment]
I wouldn't say the _projects_ participated, but individuals.

For example for react, Cees-Jan is heavily involved, but he's not the main maintainer… Thus, I wouldn't distinguish by project here.

**Comment by AndrewCarterUK** [comment]
Most of my work here is motivated by [PHPFastCGI](https://github.com/PHPFastCGI/FastCGIDaemon) - but I'm not sure if that counts as a participating project?

**Comment by WyriHaximus** [comment]
The title could be `Projects with participating members`, as @bwoebi points out the projects are not participating per se their members are. Honestly I'm in doubt about this

**Comment by jmalloc** [comment]
If you're interested in an outsider's two cents, I think it would be more useful to prospective users and implementors to list projects that adhere to the interfaces, rather than contributing projects, and I believe this is the original intent of @mnapoli's Reddit comment.

If you're reluctant to include such a list in the README file - which is understandable, as it will hopefully grow considerably :) - then perhaps taking a leaf out of ReactPHP's book and offering a user-editable wiki page could be useful?

**Comment by mnapoli** [comment]
Well now that the project has a release, it might be interesting to list projects that are compatible with this standard (either as provider or as consumer).

For example the list in container-interop: https://github.com/container-interop/container-interop#compatible-projects

**Comment by kelunik** [comment]
@jmalloc @mnapoli The number of projects implementing the `Loop` will probably not grow. Amp will get a version 2.0, React will work with an adapter of Amp 2.0 probably, don't know what will happen to Icicle, @trowski?

So it seems we're rather aiming at a common implementation not only a common interface currently.

**Comment by bwoebi** [comment]
@kelunik Don't know what will happen with React yet… and perhaps Guzzle will also have their own loop implementation … We'll see what future brings.

**Comment by WyriHaximus** [comment]
> We'll see what future brings.

Exactly! I'll start writing a bidirectional adapter for react first. As a member and not the leader I can't guarantee anything. But this is an initiative I personally consider to be hugely beneficial for the async php community, so yeah I intend to get it to react one way or the other. The adapter is way one and hopefully the first step  :smile: .

**Comment by mnapoli** [comment]
@kelunik right but projects will use this? If so, it seems interesting to list them? This discussion make it sound complicated :)

**Comment by bwoebi** [comment]
Sure, _will_. But we have no released versions of projects actually using it. amphp/amp v2 will probably get some release (or pre-release at least) in not too distant future I guess.

_Then_ we can add it ;-)

**Comment by mnapoli** [comment]
:+1:

**Comment by trowski** [comment]
@kelunik Icicle will be abandoned in favor of Amp v2. The APIs are nearly identical at this point, no use having two competing projects offering almost the exact same thing.

**Comment by kelunik** [comment]
We have the implementations and compatible packages listed now. The spec is written by individuals, not projects. I'll close this one now. If someone wants to see more in the README, just respond or reopen.
