### ISSUE TITLE
storeState / fetchState naming

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#88]
I think we should change the names to `setState` and `getState`. What do you think?

**Comment by WyriHaximus** [comment]
Agreed, store/fetch implies there is more going on in the back ground rather than an atomic set/get :+1:

**Comment by bwoebi** [comment]
https://github.com/async-interop/event-loop/pull/31#issuecomment-219178341

>  I don't like `setState`, it makes me think it's an event loop state, not something not actually related to the loop driver but just data.

What now? What made you change your mind?

**Comment by kelunik** [comment]
> What now? What made you change your mind?

It's actually in the driver now.

**Comment by bwoebi** [comment]
Well … I'm pretty much ambivalent on this; if you think the change is necessary, fine for me.

**Comment by trowski** [comment]
Either way is acceptable IMO. As methods most will not use, I don't much care.

**Comment by kelunik** [comment]
Closing as PR is merged.
