### ISSUE TITLE
Do we really need tick()?

### ISSUE THREAD

**Issue by bwoebi** [async-interop/event-loop#9]
What exactly is the purpose of `tick()` except leaking the internal detail of being "ticked"?

A tick is easily simulated with (using Amp's interface):

``` PHP
$reactor->immediately(function() use ($reactor) {
    $reactor->immediately(function() use ($reactor) {
        $reactor->stop();
    });
});
$reactor->run();
```

It's a nice helper function, but does it really have to be directly accessible? Also, the only usage for `tick()`'s I've seen so far is to wait for a single promise, which can be also written as:

``` PHP
$promise->when(function() use ($reactor) {
    $reactor->stop();
});
$reactor->run();
```

**Comment by WyriHaximus** [comment]
Honestly the only time I had to use `tick()` was when I had to force the loop to iterate to achieve compatibility with Guzzle. It's a bad thing to do from within a running loop but couldn't find another way at the time.

**Comment by bwoebi** [comment]
You mean like … you tried to tick() two loops at a same time?

That sounds horrible … (and even then you just could poll the guzzle event loop each 50 ms for example)

**Comment by trowski** [comment]
I've used it to provide compatibility with synchronous APIs. Your example stops the loop after the promise is resolved, but perhaps you just wanted to tick the loop manually, stopping control flow until the promise is resolved, but otherwise allowing the loop to continue running.

It's inelegant and horrible in an actual async program, but sometimes you want to mix sync and async. That's the only time I see `tick()` being useful. If there's a better way to do it, I'm listening because fundamentally I agree, `tick()` really shouldn't be exposed.

**Comment by WyriHaximus** [comment]
No I forced the currently running loop to iterate over and over again until the request guzzle is waiting for is done. I'll have a look at it again to see if there is a better way now or that I've missed but yes it is a miserable but effective way of doing it.

**Comment by bwoebi** [comment]
@trowski You mean like stopping everything else until a specific task is completed? … Could you please rephrase what you mean?

**Comment by trowski** [comment]
@bwoebi Here's an example:

``` php
function wait(Promise $promise, EventLoop $loop)
    while ($promise->isPending()) {
        // Ticks the event loop, dispatching events, but this control flow context waits here.
        $loop->tick();
    }

    return $promise->getResult();
}
```

The event loop can be running before and after `wait()` is run, but it allows a promise to be synchronously waited on within a running event loop. It's far from ideal, but it works. Not something I'd recommend in a truly async program.

**Comment by WyriHaximus** [comment]
@trowski used the exact same thing in my guzzle handler :+1: . Not something I enjoyed doing but it was effective. One of the problems is that your callstack keeps increasing and memory keeps building until the entire stack is resolved.

**Comment by bwoebi** [comment]
Oh, you want to invoke tick() while running … That's something which Amp outright forbids https://github.com/amphp/amp/blob/master/lib/NativeReactor.php#L147-L151

Hmm

I'm not sure why you'd want to do that though … Also, uhm … isn't that working for exactly one single Promise, if you have two wait()'s, you'll only be able to resolve the first one after the second one has resolved… that sounds really awkward and I'm not sure if we should support that…

But I don't get why you can just call $reactor->run() and $reactor->stop() there in an immediate (assuming that we'll allow nesting `run()` calls (?))

**Comment by kelunik** [comment]
I think we should implement the wait mechanism just as

``` php
function wait(Promise $promise) {
    run(coroutine(function() (&$value) {
        $value = yield $promise;
        stop();
    });

    return $value;
}
```

**Comment by bwoebi** [comment]
Precisely this ;-)

Which actually is the same than

``` PHP
$promise->when(function() use ($reactor) {
    $reactor->stop();
});
$reactor->run();
```

from the initial post, just formulated in another way.

**Comment by kelunik** [comment]
`wait` should only be used in tests / legacy apps that mix both (async & sync) frequently, I think the small overhead of emulating it is fine there for the sake of not leaking `tick`.

**Comment by trowski** [comment]
@kelunik I agree, outside of integrating async with sync code, tests are only other place I've ever used `wait()` or `tick()`. Let's not have `tick()` as part of the interface and emulate `wait()` as @bwoebi suggested. Best of both worlds.

**Comment by kelunik** [comment]
@WyriHaximus Do you agree, too? In that case we can close this issue as well.

**Comment by AndrewCarterUK** [comment]
As per usual, I'll close and if anyone has anything to add we can reopen

**Comment by WyriHaximus** [comment]
@kelunik agreed :)
