### ISSUE TITLE
Specify how error handler works

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#95]
Currently, there's nothing that describes when the error handler is invoked and when the error couldn't be handled by the error handler. My guess is that the error handler should rethrow if it can't handle the exception and otherwise do nothing. Return value doesn't matter.

**Comment by bwoebi** [comment]
Feel free to PR this, I'd like to read the actual wording on that.

**Comment by kelunik** [comment]
Please read the PR and comment. I'm not that happy with the current wording, maybe someone has improvements.

**Comment by bwoebi** [comment]
Closed as per #110 being merged.
