### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by kelunik** [async-interop/event-loop#96]
This issue relates to #11. Looks like this vote doesn't pass: https://groups.google.com/d/msg/php-fig/S-URR0_h2U0/1hpJhkgiDwAJ. If we want this standard to be a FIG standard, we have to adjust our class names.
- `Driver` → `AbstractDriver`
- `DriverFactory` → `DriverFactoryInterface`

We also might want to follow other PSRs and use exception interfaces instead of classes. We might even want to do that independently.

**Comment by bwoebi** [comment]
We do not have to be integrated into FIG either. Async-Interop can as well just reside as defacto standard between the different Loop implementations.

FIG is really just a way to make things "more official".

Let's defer this until we know whether we'll be in FIG or not.

---

I haven't understood the point of using Exception interfaces. I mean, I can just trivially extend the class instead, in case I really want my own class. For everything else we can just easily use the exceptions defined here without an extra class in the codebase implementing event-loop.

**Comment by kelunik** [comment]
Following the discussion in #11 there seems to be consensus to keep our current names, no matter what happens with FIG.
